### ISSUE TITLE
ModuleNotFoundError: No module named 'lavis.processors.randaugment'

### ISSUE THREAD

**Issue by Yuehongzhe** [Pointcept/GPT4Point#26]
您好，请问我出现了这个错误，lavis库已经安了，请问怎么解决呢，非常感谢

(gpt4point) wsco2@vm-4090-2:/media/Disk/GPT4Point-main$ python -m torch.distributed.run --master_port=32339 --nproc_per_node=4 train.py --cfg-path lavis/projects/gpt4point/train/pretrain_stage1_cap3d.yaml
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "train.py", line 18, in <module>
Traceback (most recent call last):
  File "train.py", line 18, in <module>
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import lavis.tasks as tasks
  File "/media/Disk/GPT4Point-main/lavis/__init__.py", line 15, in <module>
    import lavis.tasks as tasks
  File "/media/Disk/GPT4Point-main/lavis/__init__.py", line 15, in <module>
    import lavis.tasks as tasks
  File "/media/Disk/GPT4Point-main/lavis/__init__.py", line 15, in <module>
    from lavis.datasets.builders import *
  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/__init__.py", line 8, in <module>
    from lavis.datasets.builders import *
  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/__init__.py", line 8, in <module>
    from lavis.datasets.builders import *
  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/__init__.py", line 8, in <module>
    from lavis.datasets.builders.base_dataset_builder import load_dataset_config
  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/base_dataset_builder.py", line 17, in <module>
    from lavis.datasets.builders.base_dataset_builder import load_dataset_config    
from lavis.datasets.builders.base_dataset_builder import load_dataset_config  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/base_dataset_builder.py", line 17, in <module>

      File "/media/Disk/GPT4Point-main/lavis/datasets/builders/base_dataset_builder.py", line 17, in <module>
from lavis.processors.base_processor import BaseProcessor
  File "/media/Disk/GPT4Point-main/lavis/processors/__init__.py", line 9, in <module>
    from lavis.processors.base_processor import BaseProcessor    
    from lavis.processors.base_processor import BaseProcessor  File "/media/Disk/GPT4Point-main/lavis/processors/__init__.py", line 9, in <module>
from lavis.processors.blip_processors import (

  File "/media/Disk/GPT4Point-main/lavis/processors/__init__.py", line 9, in <module>
  File "/media/Disk/GPT4Point-main/lavis/processors/blip_processors.py", line 12, in <module>
    from lavis.processors.blip_processors import (
      File "/media/Disk/GPT4Point-main/lavis/processors/blip_processors.py", line 12, in <module>
from lavis.processors.blip_processors import (
      File "/media/Disk/GPT4Point-main/lavis/processors/blip_processors.py", line 12, in <module>
from lavis.processors.randaugment import RandomAugment
ModuleNotFoundError: No module named 'lavis.processors.randaugment'
    from lavis.processors.randaugment import RandomAugment
    from lavis.processors.randaugment import RandomAugmentModuleNotFoundError: 
No module named 'lavis.processors.randaugment'
ModuleNotFoundError: No module named 'lavis.processors.randaugment'
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import lavis.tasks as tasks
  File "/media/Disk/GPT4Point-main/lavis/__init__.py", line 15, in <module>
    from lavis.datasets.builders import *
  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/__init__.py", line 8, in <module>
    from lavis.datasets.builders.base_dataset_builder import load_dataset_config
  File "/media/Disk/GPT4Point-main/lavis/datasets/builders/base_dataset_builder.py", line 17, in <module>
    from lavis.processors.base_processor import BaseProcessor
  File "/media/Disk/GPT4Point-main/lavis/processors/__init__.py", line 9, in <module>
    from lavis.processors.blip_processors import (
  File "/media/Disk/GPT4Point-main/lavis/processors/blip_processors.py", line 12, in <module>
    from lavis.processors.randaugment import RandomAugment
ModuleNotFoundError: No module named 'lavis.processors.randaugment'
E0727 09:37:46.280423 139655266981056 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 34520) of binary: /home/wsco2/anaconda3/envs/gpt4point/bin/python
Traceback (most recent call last):
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wsco2/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-27_09:37:46
  host      : vm-4090-2
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 34521)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-27_09:37:46
  host      : vm-4090-2
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 34522)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-27_09:37:46
  host      : vm-4090-2
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 34523)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-27_09:37:46
  host      : vm-4090-2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 34520)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Wk123njtririg** [comment]
您好，我也遇到了这样的问题，请问解决了吗？

**Comment by payprays** [comment]
请问你是怎么解决的？
python寻找模块是优先在同级目录，项目根目录下有lavis，因此优先索引到项目下的lavis了，但是项目里的lavis没有这个文件，因此我在`sys.path`下insert了pip安装库的路径，这些module都能找到，但是又出现了所谓 `gpt4point`模型未注册的情况，进一步排查发现与train stage 1中的config_yaml有关。至此无法进一步排查了。希望你能帮帮我。
我的具体报错如下
```
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 85, in main
    cfg = Config(parse_args())
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'gpt4point' has not been registered.
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 85, in main
    cfg = Config(parse_args())
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'gpt4point' has not been registered.
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 85, in main
    cfg = Config(parse_args())
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'gpt4point' has not been registered.
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 85, in main
    cfg = Config(parse_args())
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'gpt4point' has not been registered.
E0314 13:26:50.532728 132958349042752 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 385623) of binary: /home/test/anaconda3/envs/gpt4point/bin/python
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
...
```

**Comment by HongxiangLu** [comment]
> 请问你是怎么解决的？ python寻找模块是优先在同级目录，项目根目录下有lavis，因此优先索引到项目下的lavis了，但是项目里的lavis没有这个文件，因此我在`sys.path`下insert了pip安装库的路径，这些module都能找到，但是又出现了所谓 `gpt4point`模型未注册的情况，进一步排查发现与train stage 1中的config_yaml有关。至此无法进一步排查了。希望你能帮帮我。 我的具体报错如下
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 108, in <module>
>     main()
>   File "train.py", line 85, in main
>     cfg = Config(parse_args())
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
>     model_config = self.build_model_config(config, **user_config)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
>     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> AssertionError: Model 'gpt4point' has not been registered.
> Traceback (most recent call last):
>   File "train.py", line 108, in <module>
>     main()
>   File "train.py", line 85, in main
>     cfg = Config(parse_args())
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
>     model_config = self.build_model_config(config, **user_config)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
>     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> AssertionError: Model 'gpt4point' has not been registered.
> Traceback (most recent call last):
>   File "train.py", line 108, in <module>
>     main()
>   File "train.py", line 85, in main
>     cfg = Config(parse_args())
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
>     model_config = self.build_model_config(config, **user_config)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
>     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> AssertionError: Model 'gpt4point' has not been registered.
> Traceback (most recent call last):
>   File "train.py", line 108, in <module>
>     main()
>   File "train.py", line 85, in main
>     cfg = Config(parse_args())
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
>     model_config = self.build_model_config(config, **user_config)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
>     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> AssertionError: Model 'gpt4point' has not been registered.
> E0314 13:26:50.532728 132958349042752 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 385623) of binary: /home/test/anaconda3/envs/gpt4point/bin/python
> Traceback (most recent call last):
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 905, in <module>
>     main()
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
>     return f(*args, **kwargs)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
>     run(args)
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
>     elastic_launch(
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ...
> ```

@payprays 你好！复现项目时我也排查到了这一步，不知你有没有后续的进展？

**Comment by payprays** [comment]
> > 请问你是怎么解决的？ python寻找模块是优先在同级目录，项目根目录下有lavis，因此优先索引到项目下的lavis了，但是项目里的lavis没有这个文件，因此我在`sys.path`下insert了pip安装库的路径，这些module都能找到，但是又出现了所谓 `gpt4point`模型未注册的情况，进一步排查发现与train stage 1中的config_yaml有关。至此无法进一步排查了。希望你能帮帮我。 我的具体报错如下
> > ```
> > Traceback (most recent call last):
> >   File "train.py", line 108, in <module>
> >     main()
> >   File "train.py", line 85, in main
> >     cfg = Config(parse_args())
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
> >     model_config = self.build_model_config(config, **user_config)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
> >     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> > AssertionError: Model 'gpt4point' has not been registered.
> > Traceback (most recent call last):
> >   File "train.py", line 108, in <module>
> >     main()
> >   File "train.py", line 85, in main
> >     cfg = Config(parse_args())
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
> >     model_config = self.build_model_config(config, **user_config)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
> >     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> > AssertionError: Model 'gpt4point' has not been registered.
> > Traceback (most recent call last):
> >   File "train.py", line 108, in <module>
> >     main()
> >   File "train.py", line 85, in main
> >     cfg = Config(parse_args())
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
> >     model_config = self.build_model_config(config, **user_config)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
> >     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> > AssertionError: Model 'gpt4point' has not been registered.
> > Traceback (most recent call last):
> >   File "train.py", line 108, in <module>
> >     main()
> >   File "train.py", line 85, in main
> >     cfg = Config(parse_args())
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 33, in __init__
> >     model_config = self.build_model_config(config, **user_config)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/lavis/common/config.py", line 65, in build_model_config
> >     assert model_cls is not None, f"Model '{model.arch}' has not been registered."
> > AssertionError: Model 'gpt4point' has not been registered.
> > E0314 13:26:50.532728 132958349042752 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 385623) of binary: /home/test/anaconda3/envs/gpt4point/bin/python
> > Traceback (most recent call last):
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 905, in <module>
> >     main()
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
> >     return f(*args, **kwargs)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
> >     run(args)
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
> >     elastic_launch(
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
> >     return launch_agent(self._config, self._entrypoint, list(args))
> >   File "/home/test/anaconda3/envs/gpt4point/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
> >     raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > ...
> > ```
> 
> [@payprays](https://github.com/payprays) 你好！复现项目时我也排查到了这一步，不知你有没有后续的进展？

比较久远了，我记得当初好像给某个库的版本降了一下，还是从某个地方(huggingface)？找到了啥解决办法。
不好意思，描述的很模糊，因为时间隔的太久了。
